### ISSUE TITLE
Script for counting subword tokens of OSCAR

### ISSUE THREAD

**Issue by new5558** [PyThaiNLP/WangChanGLM#2]
Just read your [Blog](https://medium.com/@iwishcognitivedissonance/wangchanglm-the-thai-turned-multilingual-instruction-following-model-7aa9a0f51f5f), and appreciated your findings. In the blog there is a line that mentioned:

 `We trained a Thai Sentencepiece tokenizer with 16k vocab and ran it on the Thai portion of OSCAR. This results in about 1B subword tokens.` 

I tried replicating the findings using publicly available Sentencepiece tokenizers (mT5, WangchanBERTa, and XGLM) with a Thai portion of OSCAR-2301. Although these Sentencepice tokenizers absolutely have different vocab than 16k vocab tokenizer to do a direct comparison, My results are far from 1B subword tokens. 
```python
from datasets import load_dataset

dataset = load_dataset("oscar-corpus/OSCAR-2301", "th")
print(dataset)

from transformers import XGLMTokenizerFast

tokenizer_xglm = XGLMTokenizerFast.from_pretrained("facebook/xglm-7.5B")
dataset_tokenized = dataset['train'].map(lambda item: {"ids": tokenizer_xglm(item['text'])['input_ids']}, batched=True, batch_size=100000)
dataset_tokenized = dataset_tokenized.map(lambda item: {"length": len(item['ids'])})
print(dataset_tokenized)
print(sum(dataset_tokenized['length'])) #output: 10203895284 (10.2B)
```
Full Code: https://colab.research.google.com/drive/1EzLFuWIUZ3f71cmTo2fIA9_fa8X-rM2z?usp=sharing 

Can you guide me why my code did not get the same result or can you share a script that can reproduce these findings? Thank you.

**Comment by cstorm125** [comment]
Hi New. Thanks for checking out our blog and models. We did deduplication and preprocessing on it and this is from a not-yet-pulic tokenizer. I should have clarified that in the blog. Will add. Thanks.
